import '@/main';
import '@components/calc-card/calc-card';
import '@components/dropdown-date/dropdown-date';
import '@components/logo/logo';
import '@components/registration-card/registration-card';
import '@components/room-card/room-card';
import '@components/search-card/search-card';
import '@components/sign-in-card/sign-in-card';
import './cards.scss';
